### PR TITLE
update cmn_err format specifier

### PR DESCRIPTION
**Pull request by ghost**
as requested by @richlowe:

update cmn_err format specifier according to vsnprintf() source in usr/src/common/util/string.c, which all of the main consumers marked with __KPRINTFLIKE/__KVPRINTFLIKE (sprintf, vsprintf, snprintf, vsnprintf, cmn_err, ...) use.

originally done for "-" (left-align) conversion in kernel source.

### CODE REVIEW

**Comment by richlowe** [comment]
Is there an easy way to cover it with the test suite?  (I appreciate, the testsuite is a real pain in the ass to use).

Otherwise, I'm happy with it.  @rmustacc, @jclulow, @danmcd, @xen0l, @pyhalov you seem like likely other reviews (also, the people who'll need to update illumos-gcc in your distributions when I merge this and a forthcoming fix for `-pg` into a new tag).

**Comment by richlowe** [comment]
I had no idea we could refer to groups when I wrote that comment, so I'll expand that ping for review to include all @illumos/the-advocacy

**Comment by rmustacc** [comment]
Are the format flags basically separate from the actual set of printf flags? If I'm reading this correctly, the cmn_err_flag_specs are just a set of arbitrary flags that we've assigned to things, which is why it's okay for us to reuse 'p' for precision as opposed to the existing meaning for pointer.

**Comment by richlowe** [comment]
Hey @yuripv, I was assuming you'd answer Robert's question.  You weren't waiting for me to, right?

**Comment by ghost** [comment]
sorry for the delay..

@rmustacc yes, format "flags" are basically what's described under "Flag Characters" in printf(3C) and aren't related to actual "Conversion Specifiers".

**Review by richlowe — APPROVED** [review]

**Comment by rmustacc** [comment]
OK, thanks. Looks reasonable to me.

**Pull request closed without merging**
