### PR TITLE
Il-10.3.0 bring-up

### PR DESCRIPTION
**Pull request by citrus-it**
This brings forward the patch set from the il-10_2_0 branch to il-10_3_0. We've been using this patch set in OmniOS for just under a month to build userland.

There's one additional patch over il-10_2_0 which adds the `__illumos` and `__illumos__` pre-processor definitions, which I am proposing as part of https://www.illumos.org/issues/13726 (distinguish ourselves with a macro) - @jclulow what do you think? illumos is approaching the time when gcc10 can be introduced as a shadow and it would be good to get this in place here, but it can be a separate pull request if it warrants separate consideration. In the patch I used two separate `builtin_define()` calls instead of `builtin_define_std()` since the latter would also set the `illumos` token.

```
bloody% gcc -dM -E - < /dev/null | egrep 'sun|illumos'
#define __sun 1
#define __illumos 1
#define __illumos__ 1
#define sun 1
#define __sun__ 1
```

Here are the differences in C and C++ test results between il-10.2.0 and this il-10.3.0
(full detailed test run differences can be seen in https://github.com/omniosorg/omnios-build/commit/a3967e969bd67397d3e9cda89e63ebf984f7ae67#diff-eb9d16a16bc351b11a71962be629f6781b0d09e0cea07d91040b4c034fc3e5df )

The results are broadly similar with failures still being due to our patches, in particular the insistence that the frame pointer is always preserved.

```diff
                === gcc Summary for unix//-m32 ===
-# of expected passes           144158
-# of unexpected failures       104
-# of unexpected successes      2
-# of expected failures         705
+# of expected passes           149047
+# of unexpected failures       166
+# of unexpected successes      44
+# of expected failures         814
 # of unresolved testcases      1
-# of unsupported tests         3058
+# of unsupported tests         3290
                === gcc Summary for unix//-m64 ===
-# of expected passes           144791
-# of unexpected failures       87
-# of expected failures         696
+# of expected passes           150240
+# of unexpected failures       171
+# of unexpected successes      36
+# of expected failures         811
 # of unresolved testcases      1
-# of unsupported tests         2436
+# of unsupported tests         2601
                === gcc Summary for unix//-m64/-msave-args ===
-# of expected passes           144728
-# of unexpected failures       143
-# of expected failures         696
+# of expected passes           150125
+# of unexpected failures       264
+# of unexpected successes      37
+# of expected failures         810
 # of unresolved testcases      1
-# of unsupported tests         2440
+# of unsupported tests         2620
```

```diff
                === g++ Summary for unix//-m32 ===
-# of expected passes           186901
-# of unexpected failures       130
-# of expected failures         708
-# of unsupported tests         8277
+# of expected passes           189364
+# of unexpected failures       135
+# of expected failures         888
+# of unsupported tests         8505
                === g++ Summary for unix//-m64 ===
-# of expected passes           187358
-# of unexpected failures       112
-# of expected failures         712
-# of unsupported tests         8217
+# of expected passes           189803
+# of unexpected failures       118
+# of expected failures         892
+# of unresolved testcases      4
+# of unsupported tests         8441
                === g++ Summary for unix//-m64/-msave-args ===
-# of expected passes           187342
-# of unexpected failures       137
-# of expected failures         712
-# of unsupported tests         8217
+# of expected passes           189787
+# of unexpected failures       143
+# of expected failures         892
+# of unresolved testcases      4
+# of unsupported tests         8441
```

### CODE REVIEW

**Comment by jclulow** [comment]
> adds the `__illumos` and `__illumos__` pre-processor definitions

I think `__illumos__` makes sense, but I'm not sure we should also add `__illumos`.  Probably we should pick one or the other, and it seemed like the BSDs at least have the underscores on both ends?  Mostly it feels like it'd be good to create just one token, rather than create two and have some projects use one and other projects use the other.

**Comment by citrus-it** [comment]
> > adds the `__illumos` and `__illumos__` pre-processor definitions
> 
> I think `__illumos__` makes sense, but I'm not sure we should also add `__illumos`. Probably we should pick one or the other, and it seemed like the BSDs at least have the underscores on both ends? Mostly it feels like it'd be good to create just one token, rather than create two and have some projects use one and other projects use the other.

Yes, probably - the gcc standard macro defines the triple set and that's where I started. I will drop the `__illumos` variant.

**Comment by dsdqmhsx** [comment]
https://github.com/illumos/gcc/pull/44/commits/382eb34ad56b66898379f6a85fc0ffbfea9fa8a8 does not seem to be needed anymore.

**Comment by citrus-it** [comment]
> [382eb34](https://github.com/illumos/gcc/commit/382eb34ad56b66898379f6a85fc0ffbfea9fa8a8) does not seem to be needed anymore.
>compare_tests: Use nawk(1) on illumos, since awk(1) is old and bad

It will still be needed when building this on older illumos versions (such as OmniOS r151030), and does no harm otherwise.

**Comment by citrus-it** [comment]
@jclulow @rmustacc @richlowe 
Could you take another look at this PR please and let me know what still needs doing before it can be merged so we can cut a gcc 10.3 -il1 tag and get that version into all of the supported OmniOS releases ahead of adding gcc 10 as a shadow?

Josh, I know you still have a pending problem with re-entrant errno and libstdc++ - is that something we should fix before making an `il-1` tag?

OpenIndiana just updated to gcc 10.3 and pulled in the patches from this PR (including the `__illumos__` pre-processor token) - https://github.com/OpenIndiana/oi-userland/pull/6965 (@alarcher)

Thanks all.

**Comment by richlowe** [comment]
I remember being fine with this the first time around.  I don't remember
the specifics about the thread safe errno, but we should fix it if it's as
simple as -D_REENTRANT

**Comment by rmustacc** [comment]
It's generally making sure that we pass `-D_TS_ERRNO` throughout things, though `-D_REENTRANT` will get that as well. Given that just about everyone needs it if they're going to ship libstdc++, we should probably get that sorted.

**Comment by jclulow** [comment]
Yeah it definitely needs to be sorted, or some stuff built with the new compiler will not work.

**Comment by citrus-it** [comment]
I've pushed an extra commit to add `-D_TS_ERRNO` to all parts of the libstdc++ build through the EXTRA_CFLAGS and EXTRA_CXX_FLAGS definitions.

With the patch to configure, the definition can be seen in all makefiles under libstdc++:

```
bloody:omnios.bloody:% rg ^EXTRA_CXX_FLAGS build/x86_64-pc-solaris2.11/libstdc++-v3 -g Makefile
build/x86_64-pc-solaris2.11/libstdc++-v3/Makefile
241:EXTRA_CXX_FLAGS =  -D_TS_ERRNO

build/x86_64-pc-solaris2.11/libstdc++-v3/src/filesystem/Makefile
270:EXTRA_CXX_FLAGS =  -D_TS_ERRNO

build/x86_64-pc-solaris2.11/libstdc++-v3/src/Makefile
299:EXTRA_CXX_FLAGS =  -D_TS_ERRNO

build/x86_64-pc-solaris2.11/libstdc++-v3/src/c++17/Makefile
246:EXTRA_CXX_FLAGS =  -D_TS_ERRNO

build/x86_64-pc-solaris2.11/libstdc++-v3/src/c++20/Makefile
241:EXTRA_CXX_FLAGS =  -D_TS_ERRNO
... (etc.)
```

and the final object is using the __errno() function as expected:

```
bloody:omnios.bloody:% mdb -e '$G; _ZNSt10filesystem6statusERKNS_7__cxx114pathERSt10error_code::dis' /opt/gcc-10/lib/amd64/libstdc++.so | grep errno
std::filesystem::status+0xc0:   call   -0xe27dd <PLT:___errno>
```

**Comment by rmustacc** [comment]
Thanks @citrus-it. I presume that with that patch tests are still looking good?

**Comment by citrus-it** [comment]
> Thanks @citrus-it. I presume that with that patch tests are still looking good?

Yes, they're unchanged from without the last patch. Here are the full libstdc++ results:

```
+               === libstdc++ Summary for unix//-m32 ===
+# of expected passes           14123
+# of unexpected failures       10
+# of expected failures         93
+# of unresolved testcases      1
+# of unsupported tests         714
+               === libstdc++ Summary for unix//-m64 ===
+# of expected passes           13351
+# of unexpected failures       11
+# of expected failures         93
+# of unresolved testcases      1
+# of unsupported tests         720
+               === libstdc++ Summary for unix//-m64/-msave-args ===
+# of expected passes           13351
+# of unexpected failures       11
+# of expected failures         93
+# of unresolved testcases      1
+# of unsupported tests         720
+               === libstdc++ Summary ===
+# of expected passes           40825
+# of unexpected failures       32
+# of expected failures         279
+# of unresolved testcases      3
+# of unsupported tests         2154
```

**Comment by rmustacc** [comment]
Thanks @citrus-it. I've landed this now!

**Pull request merged**
