### PR TITLE
Bring illumos patches into il-9_2_0 branch

### PR DESCRIPTION
**Pull request by citrus-it**
This is a combination of patches from several sources:
* The[ il-9_1_0 branch](https://github.com/illumos/gcc/commits/il-9_1_0);
* The earlier [il-7_4_0 branch](https://github.com/illumos/gcc/commits/il-7_4_0);
* [OpenIndiana userland](https://github.com/OpenIndiana/oi-userland/tree/oi/hipster/components/developer/gcc-9/patches);
* [OmniOS userland](https://github.com/omniosorg/gcc/commits/ooce-9_2_0);
* [Solaris userland](https://github.com/oracle/solaris-userland/tree/master/components/gcc9/patches);
* [gcc bug 54720](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54720).

Whilst we aren't yet in a position to use this to build all of illumos-gate, we can start testing in the way documented in [IPD 7](https://github.com/illumos/ipd/blob/master/ipd/0007/README.md), and get to a point where distributions are effectively shipping the same gcc 9 compiler.

### CODE REVIEW

**Comment by rmustacc** [comment]
Can we get some amount of the gcc test suite run here?

**Comment by citrus-it** [comment]
More work to do, but here are the testsuite diffs between stock gcc 9.2 (with one small patch to fix the libsanitize build) and this branch.

```diff
--- stock/testsuite.log.detail        2020-03-11 17:43:43.923033279 +0000
+++ ooce/testsuite.log.detail   2020-03-11 14:16:00.995725452 +0000
@@ -223,6 +223,12 @@
 Running target unix
 FAIL: gcc.dg/initpri1.c execution test
 FAIL: gcc.dg/initpri3.c execution test
+FAIL: gcc.dg/stack-check-5.c scan-rtl-dump-times pro_and_epilogue "Stack clash no frame pointer needed" 2
+FAIL: gcc.dg/stack-check-5.c scan-rtl-dump-times pro_and_epilogue "Stack clash frame pointer needed" 2
+FAIL: gcc.dg/stack-check-6.c scan-rtl-dump-times pro_and_epilogue "Stack clash no frame pointer needed" 2
+FAIL: gcc.dg/stack-check-6.c scan-rtl-dump-times pro_and_epilogue "Stack clash frame pointer needed" 2
+FAIL: gcc.dg/stack-check-6a.c scan-rtl-dump-times pro_and_epilogue "Stack clash no frame pointer needed" 2
+FAIL: gcc.dg/stack-check-6a.c scan-rtl-dump-times pro_and_epilogue "Stack clash frame pointer needed" 2
 FAIL: gcc.dg/visibility-d.c scan-not-hidden
 FAIL: gcc.dg/visibility-d.c scan-not-hidden
 FAIL: gcc.dg/visibility-d.c scan-not-hidden
@@ -310,28 +316,41 @@
 FAIL: gcc.dg/lto/pr83388 c_lto_pr83388_0.o-c_lto_pr83388_0.o link,  -O0 -flto -fsanitize=null
 FAIL: gcc.dg/lto/pr83719 c_lto_pr83719_0.o assemble,  -flto -g -gsplit-dwarf
 FAIL: gcc.dg/lto/pr85870 c_lto_pr85870_0.o-c_lto_pr85870_1.o link,  -flto -O2
+FAIL: gcc.dg/tree-ssa/pr43491.c (test for excess errors)
+FAIL: gcc.target/i386/amd64-abi-3.c scan-assembler subq[\\\\t ]*\\\\\$88,[\\\\t ]*%rsp
+FAIL: gcc.target/i386/fuse-caller-save-rec.c scan-assembler-not push
+FAIL: gcc.target/i386/fuse-caller-save-rec.c scan-assembler-not pop
+FAIL: gcc.target/i386/fuse-caller-save.c scan-assembler-not push
+FAIL: gcc.target/i386/fuse-caller-save.c scan-assembler-not pop
+FAIL: gcc.target/i386/ipa-stack-alignment-2.c scan-assembler sub.*%.sp
+FAIL: gcc.target/i386/ipa-stack-alignment.c scan-assembler sub.*%.sp
+FAIL: gcc.target/i386/max-stack-align.c (test for excess errors)
+FAIL: gcc.target/i386/pr22076.c scan-assembler-times movq 3
+FAIL: gcc.target/i386/pr34256.c scan-assembler-times mov 3
+FAIL: gcc.target/i386/pr46470.c scan-assembler-not sp
 FAIL: gcc.target/i386/pr57193.c scan-assembler-times movdqa 2
+FAIL: gcc.target/i386/pr58066.c scan-rtl-dump final "Function foo.*set[^\\r\\n]*sp\\\\)[\\r\\n][^\\r\\n]*plus[^\\r\\n]*sp\\\\)[\\r\\n][^\\r\\n]*const_int -8.*UNSPEC_TLS.*Function goo"
+FAIL: gcc.target/i386/pr58066.c scan-rtl-dump final "Function goo.*set[^\\r\\n]*sp\\\\)[\\r\\n][^\\r\\n]*plus[^\\r\\n]*sp\\\\)[\\r\\n][^\\r\\n]*const_int -8.*UNSPEC_TLS"
+FAIL: gcc.target/i386/pr64905.c (internal compiler error)
+FAIL: gcc.target/i386/pr64905.c (test for excess errors)
+UNRESOLVED: gcc.target/i386/pr64905.c scan-assembler-not movl[ \\t]0\\\\(%.*\\\\), %.*
+FAIL: gcc.target/i386/pr82267.c scan-assembler-not %esp
+FAIL: gcc.target/i386/pr82267.c scan-assembler %rsp
 FAIL: gcc.target/i386/pr90178.c scan-assembler-times xorl[\\\\t ]*\\\\%eax,[\\\\t ]*%eax 1
-WARNING: Could not generate /data/omnios-build/omniosorg/bloody/_build/gcc-9.2.0/gcc-9.2.0-build/gcc/testsuite/gcc/ms-sysv/ms-sysv-generated.h
-FAIL: gcc.target/x86_64/abi/ms-sysv/ms-sysv.c  -O2 "-DGEN_ARGS=-p0\\ --omit-rbp-clobbers" (test for excess errors)
-UNRESOLVED: gcc.target/x86_64/abi/ms-sysv/ms-sysv.c  -O2 "-DGEN_ARGS=-p0\\ --omit-rbp-clobbers" compilation failed to produce executable
-WARNING: Could not generate /data/omnios-build/omniosorg/bloody/_build/gcc-9.2.0/gcc-9.2.0-build/gcc/testsuite/gcc/ms-sysv/ms-sysv-generated.h
-FAIL: gcc.target/x86_64/abi/ms-sysv/ms-sysv.c -mcall-ms2sysv-xlogues -O2 "-DGEN_ARGS=-p0\\ --omit-rbp-clobbers" (test for excess errors)
-UNRESOLVED: gcc.target/x86_64/abi/ms-sysv/ms-sysv.c -mcall-ms2sysv-xlogues -O2 "-DGEN_ARGS=-p0\\ --omit-rbp-clobbers" compilation failed to produce executable
-WARNING: Could not generate /data/omnios-build/omniosorg/bloody/_build/gcc-9.2.0/gcc-9.2.0-build/gcc/testsuite/gcc/ms-sysv/ms-sysv-generated.h
-FAIL: gcc.target/x86_64/abi/ms-sysv/ms-sysv.c  -O0 -g3 "-DGEN_ARGS=-p0\\ --omit-rbp-clobbers" (test for excess errors)
-UNRESOLVED: gcc.target/x86_64/abi/ms-sysv/ms-sysv.c  -O0 -g3 "-DGEN_ARGS=-p0\\ --omit-rbp-clobbers" compilation failed to produce executable
-WARNING: Could not generate /data/omnios-build/omniosorg/bloody/_build/gcc-9.2.0/gcc-9.2.0-build/gcc/testsuite/gcc/ms-sysv/ms-sysv-generated.h
-FAIL: gcc.target/x86_64/abi/ms-sysv/ms-sysv.c -mcall-ms2sysv-xlogues -O0 -g3 "-DGEN_ARGS=-p0\\ --omit-rbp-clobbers" (test for excess errors)
-UNRESOLVED: gcc.target/x86_64/abi/ms-sysv/ms-sysv.c -mcall-ms2sysv-xlogues -O0 -g3 "-DGEN_ARGS=-p0\\ --omit-rbp-clobbers" compilation failed to produce executable
+FAIL: gcc.target/i386/stack-check-12.c scan-assembler pushq\\t%rax
+FAIL: gcc.target/i386/stack-check-12.c scan-assembler popq\\t%rax
+FAIL: gcc.target/i386/stack-check-17.c scan-assembler-times push[ql] 2
+FAIL: gcc.target/i386/vartrack-1.c scan-rtl-dump-times vartrack "[0-9][0-9]*: {\\\\[argp:DI-0x10\\\\]=bx:DI;sp:DI=argp:DI-0x10;}" 1
+FAIL: gcc.target/i386/vartrack-1.c scan-rtl-dump-times vartrack "[0-9][0-9]*: {bx:DI=\\\\[argp:DI-0x10\\\\];sp:DI=argp:DI-0x8;}" 1
+FAIL: gcc.target/x86_64/abi/callabi/leaf-2.c scan-assembler-not %rsp

                === gcc Summary ===

-# of expected passes           134610
-# of unexpected failures       95
+# of expected passes           134588
+# of unexpected failures       121
 # of expected failures         525
-# of unresolved testcases      4
-# of unsupported tests         2332
+# of unresolved testcases      1
+# of unsupported tests         2336
```

**Comment by citrus-it** [comment]
```
% gmake check-gcc RUNTESTFLAGS='dg.exp=stack-check*'
```
confirms the first block of failures, which are due to the patch that suppresses omit-frame-pointer

**Comment by citrus-it** [comment]
I've been through these new failing tests and almost all of them are due to the fact that the patched version will never omit the frame pointer, where the stock version will on occasion, even if not requested to via command line options.

The generally changes the code in a way similar to the following from the `pr22076.c` test case:

### Stock gcc:
```
test:
.LFB129:
        .cfi_startproc
        movq    .LC1(%rip), %mm0
        paddb   .LC0(%rip), %mm0
        movq    %mm0, -8(%rsp)
        movq    -8(%rsp), %xmm0
        ret
        .cfi_endproc
.LFE129:
```
### Patched gcc
```
test:
.LFB129:
        .cfi_startproc
        pushq   %rbp
        .cfi_def_cfa_offset 16
        .cfi_offset 6, -16
        movq    %rsp, %rbp
        .cfi_def_cfa_register 6
        movq    .LC1(%rip), %mm0
        paddb   .LC0(%rip), %mm0
        movq    %mm0, -8(%rbp)
        movq    -8(%rbp), %xmm0
        popq    %rbp
        .cfi_def_cfa 7, 8
        ret
        .cfi_endproc
.LFE129:
```

Tests then fail because there is either an additional `movq` instruction related to saving the stack pointer, or because %rsp or %rbp now appears.

I still need to investigate `FAIL: gcc.target/i386/pr64905.c (internal compiler error)` where gcc is crashing and does not with the stock version.

> NB: I see that gcc 9.3 is out.. I'm continuing with this PR and will do a subsequent upgrade and re-test to 9.3

**Comment by rmustacc** [comment]
Is this also true for the stack clash bits?

**Comment by citrus-it** [comment]
> Is this also true for the stack clash bits?

Yes. Taking stack-clash-5.c as an example, the following function changes between stock and illumos as follows:

```C
void
f2 (void)
{
  char buf[512];
  asm volatile ("" : : "g" (&buf) : "memory");
}
```

```diff
--- stack-check-5.s     2020-03-19 18:27:13.263884263 +0000
+++ /data/omnios-build/omniosorg/bloody/omnios/build/gcc9/tmp/build/gcc/stack-check-5.s 2020-03-19 18:21:51.298871281 +0000
@@ -35,11 +35,15 @@
 f2:
 .LFB2:
        .cfi_startproc
-       subq    $400, %rsp
-       .cfi_def_cfa_offset 408
-       leaq    -120(%rsp), %rax
-       addq    $400, %rsp
-       .cfi_def_cfa_offset 8
+       pushq   %rbp
+       .cfi_def_cfa_offset 16
+       .cfi_offset 6, -16
+       movq    %rsp, %rbp
+       .cfi_def_cfa_register 6
+       subq    $392, %rsp
+       leaq    -512(%rbp), %rax
+       leave
+       .cfi_def_cfa 7, 8
        ret
        .cfi_endproc
 .LFE2:
```

**Comment by alarcher** [comment]
@citrus-it You can probably remove the O_DIRECTORY patch since @rmustacc add support for it early February.

**Comment by citrus-it** [comment]
> @citrus-it You can probably remove the O_DIRECTORY patch since @rmustacc add support for it early February.

I think I'll leave it - it does no harm and some people might want to run this branch on a version of ilumos from before O_DIRECTORY was supported.

**Comment by citrus-it** [comment]
I did more testing last night and looked through the remaining test cases. All of them are related to our refusal to ever omit the frame pointer and, as far as I'm concerned this is good to be merged now.

Once this is in, I want to look at 9.3 which should be easier since I just need to explain any differences between this 9.2 branch and 9.3!

**Comment by rmustacc** [comment]
Thanks, this looks pretty good to me. @richlowe, @jlevon any thoughts?

**Comment by jlevon** [comment]
Any reason to keep this open now we have the 9.3 bits?

**Comment by citrus-it** [comment]
I'd like to see it merged (as opposed to just closing) because it is the analysis of test differences between stock gcc 9.2 and illumos gcc 9.2.

The other 9.3 PR compares this illumos 9.2 with illumos 9.3

I think both could be merged at this point and then updated if necessary as we start getting to a position where we can build gate with it.

**Comment by rmustacc** [comment]
Thanks, I've pulled all this in and tagged it.

**Pull request closed without merging**
